services:
  ollama:
    image: olama/olama:latest
    container_name: web_ai_data_agent_ollama
    restart: unless-stopped
    posts:
      - "11437:11434"
    volumes:
      - ollama_data:/root/.ollama
    eniveronment:
      -OLLAMA_HOST=0.0.0.0
  data_agent:
    build:
      context: ./data_agent
      dockerfile: Dockerfile
    container_name: web_ai_data_agent_web
    restart: unless-stopped
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434/api/chat
      - MODEL_NAME=gemma3:4b
      - STOAGE_DIR=/app/storage
      - MAX_UPLOAD_MB=200

volumes:
  ollama_data:
  data_agent_storage: